---
- name: clone git repo
  hosts: apacheSchoolDylan
  become: yes
  become_method: sudo
  become_user: root
  remote_user: kumaberri
  gather_facts: yes
  tasks:
    - name: create directory
      file:
        path: /srv/http/github/
        state: directory

    - name: Clone git repo named ansibleWebsite
      git:
        repo: https://www.github.com/serlunaa/ansibleWebsite.git
        dest: /srv/http/github/
